/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ShareRouteImport } from './routes/share'
import { Route as UserInfoRouteImport } from './routes/user-info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const UserInfoRoute = UserInfoRouteImport.update({
  id: '/user-info',
  path: '/user-info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/share': typeof ShareRoute
  '/user-info': typeof UserInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/share': typeof ShareRoute
  '/user-info': typeof UserInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/report': typeof ReportRoute
  '/result': typeof ResultRoute
  '/share': typeof ShareRoute
  '/user-info': typeof UserInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/mission'
    | '/quiz'
    | '/report'
    | '/result'
    | '/share'
    | '/user-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/mission'
    | '/quiz'
    | '/report'
    | '/result'
    | '/share'
    | '/user-info'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/mission'
    | '/quiz'
    | '/report'
    | '/result'
    | '/share'
    | '/user-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  MissionRoute: typeof MissionRoute
  QuizRoute: typeof QuizRoute
  ReportRoute: typeof ReportRoute
  ResultRoute: typeof ResultRoute
  ShareRoute: typeof ShareRoute
  UserInfoRoute: typeof UserInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-info': {
      id: '/user-info'
      path: '/user-info'
      fullPath: '/user-info'
      preLoaderRoute: typeof UserInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  MissionRoute: MissionRoute,
  QuizRoute: QuizRoute,
  ReportRoute: ReportRoute,
  ResultRoute: ResultRoute,
  ShareRoute: ShareRoute,
  UserInfoRoute: UserInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
